Upgrading `httplib` to `0.46.0`, importing it as flake input
Upstream only has 0.30.2 of httplib ( https://github.com/NixOS/nixpkgs/blob/aa104f3f1c45bf18ec7d8845f487eb6857c98f0f/pkgs/by-name/ht/httplib/package.nix#L12 ).

This allows builds to proceed, but still fails due to
MbedTls version incompatibilities:

```
       > [ 67%] Building CXX object CMakeFiles/huenicorn.dir/src/Stream/Impl/MbedTls/DtlsClient.cpp.o
       > In file included from /build/source/build/src/src/Stream/Impl/MbedTls/DtlsClient.cpp:7:
       > /build/source/build/src/include/Huenicorn/Stream/Impl/MbedTls/MbedTlsClientImpl.hpp: In member function 'void Huenicorn::Stream::Impl::_handshake(const Huenicorn::Stream::DtlsConfig&)':
       > /build/source/build/src/include/Huenicorn/Stream/Impl/MbedTls/MbedTlsClientImpl.hpp:269:7: error: 'result' may be used uninitialized [-Werror=maybe-uninitialized]
       >   269 |       if(result != 0){
       >       |       ^~
       > /build/source/build/src/include/Huenicorn/Stream/Impl/MbedTls/MbedTlsClientImpl.hpp:256:11: note: 'result' was declared here
       >   256 |       int result;
       >       |           ^~~~~~
       > cc1plus: all warnings being treated as errors
       > make[2]: *** [CMakeFiles/huenicorn.dir/build.make:322: CMakeFiles/huenicorn.dir/src/Stream/Impl/MbedTls/DtlsClient.cpp.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:154: CMakeFiles/huenicorn.dir/all] Error 2
       > make: *** [Makefile:91: all] Error 2
       For full logs, run:
         nix log /nix/store/7g1qc5h6xq9x4hpqipj5nqcdyn9mcwzq-huenicorn.drv
```